# Generated by Django 5.2 on 2025-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavishBnB', '0002_service_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('cash_on_hand', 'Cash on Hand')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
