# Generated by Django 5.2.1 on 2025-05-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavishBnB', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
